server:
  port: ${PORT:8080}

spring:
  application:
    name: test-git-cd-ci
  datasource:
    username: ztmfiouoqruxod
    password: 1be9a173acff9bb6a2be41919262b5f8685c22c445051f87f15d66b8877cc50d
    url: jdbc:postgresql://ec2-52-48-159-67.eu-west-1.compute.amazonaws.com:5432/ddc43ul81r1of3
    driver-class-name: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    hibernate:
      ddl-auto: update